### ISSUE TITLE
Issue with products which cannot be back ordered

### ISSUE THREAD

**Issue by DanielRiera** [DanielRiera/estimated-delivery-woocommerce#14]
Hi,

There seems to be an issue with products that cannot be back-ordered. It will give a date anyway while it should be empty or maybe a message?

Thanks

[FORUM](https://wordpress.org/support/topic/issue-with-products-which-cannot-be-back-ordered/)

**Comment by Sammiess** [comment]
Hi, 

Sorry for the delay. For instance, I have a product here with this[ necklace set](https://yazzys.com/jewellery/sets/swarovski-set-with-studs/) Where one colour is in stock the other is sold out and cannot be back-ordered. However, it will give me a date although in the back-end it is set to not allow back-orders. 

thanks
