### ISSUE TITLE
Can not see in cart and checkout

### ISSUE THREAD

**Issue by DanielRiera** [DanielRiera/estimated-delivery-woocommerce#18]
Forum https://wordpress.org/support/topic/can-not-see-in-cart-and-checkout/

# Message 1

Hello

Thanks for the plugin.

I wanted to know if it only works on products, because it does not appear in the cart and in the checkout section.

Confirm if you can not see in cart and checkout?

# Message 2
I have the same question, I would like to display the estimated time also at checkout.

**Comment by sarahappy-flower** [comment]
Hola!!! De qué forma puedo hacer que aparezca en el carrito y/o checkout junto al producto? 
Gracias

**Comment by ricardoomaciel** [comment]
Same here. Daniel, presenting the dates in the cart/checkout is an essential feature. It's probably difficult to implement, but showing in the product page is not as useful. For instance, how to connect the delivery date to the shipping rate? Woocommerce does not show delivey time for free shipping. Yours is a great and unique plugin, missing only this feature.

**Comment by DanielRiera** [comment]
Hi @ricardoomaciel @sarahappy-flower 

The delivery date in the cart and chekcout is ready, it will be available in today's update.

On the other hand, the option to configure the estimated delivery for each shipment type was planned for a pro version, but due to lack of time I could not finish it.

In the next updates it will be available since I will not release pro version. :)

Regards

**Comment by ricardoomaciel** [comment]
Thanks much for the update, Daniel!

Em sáb., 18 de fev. de 2023 às 15:12, Daniel Riera ***@***.***>
escreveu:

**Comment by ClaFerro** [comment]
hi Daniel congratulations for the plug-in I can't translate the word "Estimated delivery" on cart / mini-cart and checkout into Italian with "Loco translat". 
Can you help me?
