### ISSUE TITLE
Conflict with woodmart and options for shop's holiday?

### ISSUE THREAD

**Issue by heiheiheihei9** [DanielRiera/estimated-delivery-woocommerce#24]
Hello, your plugin is great.
But there are some conflicts with woodmart, especially on the mobile screen.
Also, it is possible to add holiday dates or week day also for shops?
Thank you

**Comment by DanielRiera** [comment]
Hi, thanks! You can send a screenshot with error?

What conflicts?


Regards

**Comment by DanielRiera** [comment]
Close for no comments.
