### ISSUE TITLE
Product-CSV-Import

### ISSUE THREAD

**Issue by lagaga** [DanielRiera/estimated-delivery-woocommerce#26]
Hello
Thanks for the plugin.
I have a question about importing in the standard way from the Woocommerce plugin. (https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting)

What metas does your plugin use to enable import/export (preferably import) for products?

I would like to give the opportunity to indicate the approximate delivery dates for each product in the price list according to the plugin settings.

And another question - is the plugin supported, will there be updates?

Best regards, the plugin and your work on it is great.

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting

**Comment by DanielRiera** [comment]
Hi, sorry for delay! 

"_edw_overwrite" = 1 for Overwrite general configuration
"_edw_mode" = 1 for "Estimate date" or 2 for "Guaranteed date"
"_edw_days_outstock"
"_edw_max_days_outstock"
"_edw_disabled_days"
"_edw_days_backorders"
"_edw_max_days_backorders"
"_edw_days"
"_edw_max_days"

Thanks!

**Comment by lagaga** [comment]
Thanks a lot Daniel!
