### ISSUE TITLE
showing estimated delivery in backend admin order and frontend customer order for each product

### ISSUE THREAD

**Issue by bouroudane90** [DanielRiera/estimated-delivery-woocommerce#34]
Hello estimated delivery not chowing in frontend and backend for each product , 
the customer after ordering a product has forgotten the estimated delivery date normally it must appear in the order detail in the backend admin and frontend order custumer
Thank you

**Comment by bouroudane90** [comment]
Estimated dates are not included in order detail (admin and custumer )

**Comment by DanielRiera** [comment]
Hi, this featured is not available, dates only show for customer, I can implement this featured but I need time.

**Comment by DanielRiera** [comment]
Hi! Please check 1.3.0 version :)
