### ISSUE TITLE
French Translation Problems :

### ISSUE THREAD

**Issue by Patrickfr56** [DanielRiera/estimated-delivery-woocommerce#35]
Hi,

The French translation shows :
" Livraison estimée on 11 - 20 mars, 2023 "

The " on " is not french (english).
This is not French and it is disturbing for a French person who reads this.
It gives a bad brand image, a bad impression on the e-commerce site.

A better translation could be :

" Livraison estimée entre le 28 février et le 10 mars 2023 "
" Estimated delivery between February 28 and March 10, 2023 "
" Livraison estimée entre le 11 et le 20 mars 2023 "
OR
" Livraison estimée : 11 - 20 mars 2023 "
" Livraison estimée : 28 février - 10 mars 2023 "
OR
" Livraison estimée 11 - 20 mars 2023 "
" Livraison estimée 28 février - 10 mars 2023 "
OR
" Livraison estimée à partir du 11 au 20 mars 2023 "
" Estimated delivery from March 11 to 20, 2023 "
" Livraison estimée à partir du 28 février au 10 mars 2023 "

Please tell us How and Where we can modify / change that ?

Have a Nice Day !
Best Regards,
Patrick

**Comment by labadubdub** [comment]
Use loco translate plugin. Create your translation and change it

**Comment by Patrickfr56** [comment]
Ok,

Thank you !

Le 27/02/2023 à 10:09, labadubdub a écrit :

**Comment by Patrickfr56** [comment]
Hi,
There is another problem with the Translation in the Cart as you can in the attached file.
![Translation in Cart - ESTIMATED DELIVERY](https://user-images.githubusercontent.com/126238450/222123385-41315385-23ee-4ead-b6f1-c1157c56b194.jpg)
I don't see in Loco the way to change that ?
Best Regards,
Patrick

**Comment by DanielRiera** [comment]
I updated POT files, download master branch and update your plugin.

Try and tell me if is correct, the translation string is "Estimated delivery".

Regards

**Comment by Patrickfr56** [comment]
Hi,

I deleted the Plugin.
Deleted all the elements with Advanced DB Cleaner*PRO*

Then I reinstalled the Plugin.
But it is still the same.
See enclosed pictures.

Regards,
Patrick

Le 03/03/2023 à 12:35, Daniel Riera a écrit :

**Comment by DanielRiera** [comment]
Close duplicate #38 same user.
