### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by labadubdub** [DanielRiera/estimated-delivery-woocommerce#36]
Loco translate plugin helps to translate almost all lines of the your plugin. But the "Estimated delivery" line in the cart, mini cart, and checkout page does not translate. How can I translate this line?
![screenshot](https://user-images.githubusercontent.com/126457646/221522092-ec3640df-44fc-4cfe-912a-58e225f5cdba.PNG)
Thank you for your help, it means a lot to me.

**Comment by ClaFerro** [comment]
i have the same problem, "Loco Translate" doesn't translate

**Comment by DanielRiera** [comment]
Is a duplicate #35
