### ISSUE TITLE
Translation Problem in Cart

### ISSUE THREAD

**Issue by Patrickfr56** [DanielRiera/estimated-delivery-woocommerce#38]
Hi,

Still the same translation problem in the Cart.
"ESTIMATED DELIVERY:" can not be translated in Loco Plugin.

I'm sorry, I have not seen an answer to solve this problem ?
Do you have a solution for that ?

Regards,
Patrick
![Translation in Cart - 4](https://user-images.githubusercontent.com/126238450/225375650-218eb87e-a7bf-4077-9ab4-b50c10f1b273.jpg)

**Comment by DanielRiera** [comment]
Hi

Check translate "Estimated Delivery" only.

Regards,
