### ISSUE TITLE
Delivery Date Or estimate Date Not showing

### ISSUE THREAD

**Issue by sultanbb24** [DanielRiera/estimated-delivery-woocommerce#40]
Hello Daniel,
Thank you so much for building estimate delivery woocommerce. I'm using this plugin but the delivery date not showing on woocommerce thank you page & Order details page ( On back-end for admin). Can you let me know how can i show or guide me?
Thanks 
Mahmud

**Comment by DanielRiera** [comment]
Hi! Please check 1.3.0 version :)
