### ISSUE TITLE
Working days

### ISSUE THREAD

**Issue by fouli86** [DanielRiera/estimated-delivery-woocommerce#41]
Hello, 

I was wandering if you could add besides the days that NO shipments are made, also the working days. In my case, deliveries take between 4-10 working days, so the calculation is wrong. 

Thanks anyway for this product.

Kind regards, 
Fay

**Comment by DanielRiera** [comment]
Hi thank you for opening this, can you explain what you need?

**Comment by fouli86** [comment]
Hello,

Thank you for the immediate response.  The extension only takes account the days that no shipments are made, not the working days in general. I tell my customers that the estimate delivery is between 4-10 working days (working days are Monday to Friday), which is maximum 2 weeks time. I set "Days for Delivery" to 4, the "Max Days for Delivery" to 10 and "Maximum Time" to 15:00, but the extension doesn't calculate the days correctly. It shows a range between 3 working days and 10 days, including the weekend that no shipments are made. More specifically, at the moment it is the 4th of May, 20:42. The range should have been between 10-18 May, but it is 9-15 May. I wish I could explain it better, but i think it would help to see for yourself. Do you have any suggestion on how to set the days in a better way?

Thanks in advance

Kind regards,
Fay
________________________________

**Comment by DanielRiera** [comment]
You can check timezone on wordpress settings?

Can you check what date and time is shown in the maximum time? (On field description) now: .....

Regards

**Comment by fouli86** [comment]
I tried with multiple values, nothing changed. The maximum time is correct:  (Server time) HH:mm now is 2023-05-04 22:38.

Kind regards,
Fay
________________________________

**Comment by DanielRiera** [comment]
Can you send me global plugin configuration?

**Comment by fouli86** [comment]
Hello,

Let's see:


  *   Use AJAX  -  disabled
  *   Delivery same day  - disabled
  *   Show date on order (Admin and Customer)   - enabled
  *   Show date Products Lists  -  disabled
  *   Maximum Time  -  12:30 PM
  *   Use Relative Dates  -  disabled
  *   Days for Delivery  -  in global configuration it is set to 1, it is 4 in some products
  *   Max Days for Delivery  - in global configuration it is set to 3, it is 10 in some products
  *   Days for Delivery out of stock - blank
  *   Max Days for Delivery out of stock - 0
  *   Days for Delivery Backorders  - blank
  *   Max Days for Delivery Backorders  - 0
  *   Estimated or Guaranteed - Estimated
  *   Days disabled  -  Saturday, Sunday
  *   Position - After cart button

Kind regards,
Fay
________________________________

**Comment by DanielRiera** [comment]
Hi @fouli86 ! You can try this.

Download plugin by this link, is a branch and try if is correct, check your Time Max, i saw an error on my side.

[ISSUE41 BRANCH](https://github.com/DanielRiera/estimated-delivery-woocommerce/archive/refs/heads/issue41.zip)

Regards, if is correct post a message for update plugin :)

**Comment by fouli86** [comment]
Hello!

The 4-10 working days combination works like a charm, the 1-3 working days combination counts from tomorrow (it is Sunday, a day that no shipments are made) but shows correctly the third working day. More specifically, it should show 8-10 May, but it shows 7-10 May.

Kind regards,
Fay

________________________________

**Comment by DanielRiera** [comment]
Hi @fouli86 !, you can download again on this branch and test again, sorry for this.

[Issue 41](https://github.com/DanielRiera/estimated-delivery-woocommerce/archive/refs/heads/issue41.zip)

**Comment by fouli86** [comment]
Hello,

Sorry for this but it is still not working properly. At the moment, it is past Maximum Time (it is set to 12:30PM), the combination 1-3 working days shows 9-10 May, (it should have been 9-11 May), and the combination 4-10 days shows 13-19 May (it should have been 12-22 May). The 13th of May is Saturday, we do not make shipments on Saturday.

Kind regards,
Fay
________________________________

**Comment by DanielRiera** [comment]
Sorry for this, thanks for test, i working on this, don´t have much free time.

**Comment by DanielRiera** [comment]
Hi @fouli86

You can download new version from WordPress plugin repository, i updated with @elrosa PR.

Thanks and sorry for delay
