### ISSUE TITLE
Disabled days ignored since last version

### ISSUE THREAD

**Issue by elrosa** [DanielRiera/estimated-delivery-woocommerce#42]
Since the latest version, disabled days setting is ignored.
My current date is May 2nd. Typical deliveries take between 2 to 3 working days. However, there are no deliveries from Wednesday until the end of the week; I selected these days as "disabled days".
![Screenshot_20230502_202925_com android chrome~2](https://user-images.githubusercontent.com/430030/235755291-2b4a4b52-2f86-4ab7-8f5f-f5e6fb7d83c4.jpg)

Before the update, this setting was working as expected: if expected delivery date fell on a disabled day, it was moved to a next available date. However, now it's just adding 2-3 days to today's date and ignoring disabled days.

![Screenshot_20230502_202944_com android chrome~3](https://user-images.githubusercontent.com/430030/235756898-2c673c5d-111b-4296-a3bd-bcc98a0890d9.jpg)

The screenshot is in Polish, text below button says: estimated delivery on 4-5th May. This is Thursday and Friday, both days are disabled. I'd expect 8-9th May instead (Monday-Tuesday). 

My website timezone is Europe/Warsaw (UTC+2). The server time is UTC, but changing timezone in WordPress doesn't help.

**Comment by DanielRiera** [comment]
Hi @elrosa  yes... Sorry 1.3.2 version fix this and add support for WCFM Multivendor. You can try new versión :)

Regards

**Comment by elrosa** [comment]
I can confirm it was fixed. Thank you! :)
