### ISSUE TITLE
Delivery Timeframe on my order tracking page

### ISSUE THREAD

**Issue by Alorasa** [DanielRiera/estimated-delivery-woocommerce#45]
Hi 

We created an order tracking page using a short code, is there a way to automatically add the estimated delivery timeframe on the tracking page and also auto revise the date if we fail to meet a certain milestone date?

**Comment by DanielRiera** [comment]
Hi, You can explain this? a example

Thanks

**Comment by Adioman** [comment]
Hi, I need this too. Delivery for the goods is scheduled for December 20, the supplier has transferred the goods to the delivery service, for some reason the delivery is delayed, it is necessary that the customer knows that the delivery is delayed for example until December 22

**Comment by DanielRiera** [comment]
Hi! 

This plugin does not have this purpose at least in its current version.

It only shows the delivery date according to the current configuration

This plugin does not notify the user at any time.
