### ISSUE TITLE
Maximum Time not working

### ISSUE THREAD

**Issue by kodkodak** [DanielRiera/estimated-delivery-woocommerce#46]
Hello, in first place, maybe i am missundersting but.

What is Max Time setting for? For what i understand it means, that when its set to 14 00, then value selected in Days to Delivery is applied. Lets say i have 1 day. But when somone order after that set time - lets says 15 30, it will add one more day to delivery? So it will takes two now?

Because thats exactly what i want it to do, but for some reason, its not working. When i set any time in Max Time setting and hit save, it shows empty time slots again when it refresh.

![image](https://user-images.githubusercontent.com/132880310/236757615-2472ec98-f630-4f2a-8dbf-ca7db4a92d81.png)

Any help? Btw, lovely plugin

**Comment by DanielRiera** [comment]
Hi yes sorry, is a bug, next update work well

Thanks

**Comment by kodkodak** [comment]
Thanks, when is updated coming?

**Comment by DanielRiera** [comment]
This week promise 🙏

**Comment by DanielRiera** [comment]
Update is available 1.3.3
