### ISSUE TITLE
Responsive screen missing display of delivery estimate on product listing page

### ISSUE THREAD

**Issue by nabeel5590** [DanielRiera/estimated-delivery-woocommerce#47]
Hi, 
Thanks for the beautiful plugin btw. Love it totally. 

i'm having this issue where the delivery time is not getting displayed on mobile responsive screen on product listing page. I'm using Flatsome theme but for some reason the delivery time does show on Checkout page (mobile) but not on Product list page. But everything is working fine on desktop screen. 

<img width="509" alt="Screenshot 2023-05-14 at 4 18 49 AM" src="https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/133545449/e3102956-9bdd-4d40-a929-8436c2ba56e3">

Just want to know if there's something i'm missing or option to be enabled or just some feature we're missing here. 

Thanks.

**Comment by DanielRiera** [comment]
Hi! You can provide me a link? I check this.

Regards
