### ISSUE TITLE
Compatibility with WPML

### ISSUE THREAD

**Issue by grzegorzkunicki** [DanielRiera/estimated-delivery-woocommerce#49]
I am experiencing an issue with WPML translations on my website. Despite having translated the strings using WPML, the widget is displaying the Polish (PL) version instead of the German (DE) version.

Estimated delivery%s %s is shown in Polish
Month name in the date is shown in Polish

I would appreciate your assistance in resolving this issue. Please let me know if you need any further information or access to the site to diagnose the problem.

Thank you for your support!

**Comment by Sammiess** [comment]
It is working perfectly with WPML, there are no issues
