### ISSUE TITLE
MultiVendorX Compatibility

### ISSUE THREAD

**Issue by moumitahalder** [DanielRiera/estimated-delivery-woocommerce#50]
Hi, as shared here https://wordpress.org/support/topic/multivendorx-compatibility-6/, we want to confirm whether "Estimated Delivery for Woocommerce" is compatible with MultiVendorX.

We know you have mentioned that this is compatible with WCMp. But we need to make sure this is also compatible with MultiVendorX so we can add the same info in our Third Party compatible page link.

**Comment by DanielRiera** [comment]
Hi, you can share your plugin and i can check if is compatible.
