### ISSUE TITLE
Error with delivery dates

### ISSUE THREAD

**Issue by Gluvu2023** [DanielRiera/estimated-delivery-woocommerce#51]
I recently deactivated the plugin to solve a problem, before that the plugin worked perfect, then when I reactivated it all the products show the same day delivery date, even though each one is set for different delivery days. How can I solve it

**Comment by nivito** [comment]
Same issue, comment here to see if any reply. Thanks

**Comment by DanielRiera** [comment]
Solved on 1.4.3 version 

Thanks!
