### ISSUE TITLE
Holidays and dates off from the delivery

### ISSUE THREAD

**Issue by mehowmeh** [DanielRiera/estimated-delivery-woocommerce#54]
Hello,
Tomorrow, November 1st, there is a non-working national holiday in Poland which made me thinking about the topic of days off from the delivery. Is there any option to select such dates? I ask not only because of the courier services that won't be working too during these days, but also due to any potential vacation leaves that we might plan in our business (we don't have many employees). That would be great if we could plan such things upfront and simply enter the days off in advance in the settings of your plugin.

I will be glad to hear if such an option is possible right now or if the feature might be planned for the future release.

Greetings,
Michał

**Comment by DanielRiera** [comment]
Hi! i add this on next wait 1.3.5 version.

Thanks!
