### ISSUE TITLE
WCFM Compatibility

### ISSUE THREAD

**Issue by Adioman** [DanielRiera/estimated-delivery-woocommerce#56]
Hello, I use WCFM and set the estimated delivery for WooCommerce, as an administrator I can set up uniform conditions for everyone, but my sellers do not see the settings, you write that the plugin is compatible with WCFM

**Comment by Adioman** [comment]
?

**Comment by DanielRiera** [comment]
From Wordpress Forum: Hi! You can send me a screenshot with vendor form ? Thanks!

**Comment by Adioman** [comment]
Hello, Now we don't see any settings at all for vendors.
Your plugin is incompatible with HPOS, please check it out

![Снимок экрана 2023-12-10 221110](https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/48056334/9d18e12a-56a0-40bb-b538-83f2dd17bfed)
![Снимок экрана 2023-12-10 221339](https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/48056334/8338c79c-ac46-4968-9da8-72aa55ac2a43)

**Comment by DanielRiera** [comment]
Hi!, #53 is available on next version. I check this for WCFM.

Thanks!

**Comment by DanielRiera** [comment]
Hi! This plugin only work on edit product for vendors, when sellers edit product see "Estimate Delivery" tab.

I work on this for new products, but now is only can edit.

**Comment by Adioman** [comment]
Hi, any updates on this topic?

**Comment by DanielRiera** [comment]
Hi @Adioman,

This work for "Edit Product".
