### ISSUE TITLE
Difference between date on product page and cart page

### ISSUE THREAD

**Issue by LuizaGoj** [DanielRiera/estimated-delivery-woocommerce#59]
Hi! I've got the problem that on the product page time of delivery is displayed correctly, but when I add the product to the cart, it changes (elongates) and my customers see longer time of the delivery, even though the product is in stock, which is unfortunate.

Could you please help me with it?

**Comment by DanielRiera** [comment]
Hi! Sorry for dalay.

You can send me a link for your site?

Regards

**Comment by LuizaGoj** [comment]
Hi!

Thank you for response. It's akp24.pl :) And I see there is problem also
with estimated delivery time on products that are available on stock, also
on their pages, not only in cart. It doesn't change.
IE:
https://akp24.pl/produkt/ek-r-h-rotametr-tworzywowy-z-zaworem-i-pokretlem-dla-gazow-%c2%bc-0-1-90-nl-min-powietrza/
- see 0.2 - 18 Nl/min variation, which is in stock.



śr., 3 kwi 2024 o 01:33 Daniel Riera ***@***.***> napisał(a):

**Comment by DanielRiera** [comment]
Hi! @LuizaGoj, i going to try this issue. I don't know when I will be able to look at it as I don't have much time but I will keep it in mind.

I have tried adding a product to the cart and the date shown is the same as the date shown on the product before adding it.

**Comment by LuizaGoj** [comment]
Hi Daniel,

If you could spare a moment from your time, I would be thankful.
I checked it once again and the delivery date of the products in stock is
still not the same on product page and in cart.
for example:
https://akp24.pl/produkt/wirnikowy-wskaznik-przeplywu-dn25-1/?attribute_pa_rodzaj-przylacza=bsp&attribute_pa_material-obudowy=stal-nierdzewna
.
I don't know where these differences are coming from.
Screens below:
[image: image.png]
[image: image.png]



pon., 8 kwi 2024 o 17:24 Daniel Riera ***@***.***> napisał(a):

**Comment by DanielRiera** [comment]
Hi, you check this with last version?
