### ISSUE TITLE
Need help with WCFM

### ISSUE THREAD

**Issue by Adioman** [DanielRiera/estimated-delivery-woocommerce#61]
Hello! We can set the delivery date for each item of a WCFM supplier, but when the items are loaded using import, for example the supplier uploads 30,000 items, it is very inconvenient for the supplier to manually add the delivery date! Add setting for all wcfm vendor products.

**Comment by DanielRiera** [comment]
Hi @Adioman you import system support metadata?

**Comment by Adioman** [comment]
We use the standard Woocommerce import from a .CSV file

**Comment by DanielRiera** [comment]
You need add metadata to product for this.

Example
| Key | Type | Values | Required |
|--------|--------|--------|--------|
| _edw_disabled_days | array | ['Mon', 'Tue', 'Wed', 'Thu','Fri','Sat','Sun'] | false |
| _edw_max_days | string | Max delivered days | false |
| _edw_days | string | Min delivered days | true |
| _edw_days_outstock | string | Min delivered days (outstock) | false |
| _edw_max_days_outstock | string | Max delivered days (outstock) | false |
| _edw_mode | string | 1: Estimated or 2: Guaranteed | true |
| _edw_days_backorders | string | Min delivered days (backorders) | false |
| _edw_max_days_backorders | string | Max delivered days (backorders) | false |
| _edw_overwrite | string | 1 active, 2 disabled | true |

If you create product with this metadata, the product show dates.

Regards!
