### ISSUE TITLE
Estimate Delivery Date not showing a range

### ISSUE THREAD

**Issue by mopianer** [DanielRiera/estimated-delivery-woocommerce#63]
Hi, Daniel 
Thanks for developing the plugin, it comes very handy!
My problem here is I put days in delivery and max delivery, but on product page, it still shows today's date.
Please see below:
<img width="530" alt="plugin" src="https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/167860507/cac5f52e-76dd-4593-8805-d463cbc3a463">
<img width="334" alt="shop" src="https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/167860507/0877e245-3009-45b0-ad06-7ab542b291db">

Thanks!

**Comment by nivito** [comment]
Same here, ive been trying every possible combination and the date I see on the products is the same. Uninstall, intalled again, same issue

**Comment by DanielRiera** [comment]
This is fixed on last version 1.4.3

Thanks!
