### ISSUE TITLE
Remove the display of the delivery estimate on the floating bar on the product pages

### ISSUE THREAD

**Issue by Jerem6999** [DanielRiera/estimated-delivery-woocommerce#65]
Hello,

First, thank you for this extension and for the work you do.

Nevertheless, I have a small problem, the display of the delivery estimate in the floating bar on my product pages worries me about the phone screens, making it too loaded. Would you have a way to remove the display at this level?

Thank you in advance for your answer.

![IMG_8832](https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/100757846/0fb21639-d3e7-4d65-9549-ceb692b5bba0)

**Comment by DanielRiera** [comment]
HI, mmm you theme use product list template for this, so you can add CSS for hidden this block.

Add this to your custom CSS code:

`.ct-floating-bar-actions .edw_date {
    display: none;
}`
