### ISSUE TITLE
update csv all import woocommerce

### ISSUE THREAD

**Issue by sanoterm** [DanielRiera/estimated-delivery-woocommerce#66]
Hello, I have a problem, I'm trying to upload products to wordpress with csv and activate the personalized estimated delivery option depending on the product _edw_overwrite I set 1 to activate and it doesn't activate, it takes the days in the product and the days that are not delivered Saturday and Sunday only that it doesn't activate the option

**Comment by DanielRiera** [comment]
Hi! Check 1.4.5 version, fix this and more :)

**Comment by sanoterm** [comment]
Ya esta muchas gracias
